name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.0.0a2
      - name: Install OpenBLAS
        run: sudo apt-get update && sudo apt-get install libopenblas-dev        
      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
